### ISSUE TITLE
unbind elements

### ISSUE THREAD

**Issue by ronny332** [iameugenejo/ngScrollTo#13]
Hi,

seemingly this repo is not longer maintained, but for everyone (like me), who will use the code today, think about adding a small change to the directive:

```
.directive('scrollTo', ['ScrollTo', function (ScrollTo) {
  return {
    restrict: "AC",
    compile: function () {

      return function (scope, element, attr) {
        var handler = function () {
          ScrollTo.idOrName(attr.scrollTo, attr.offset);
        };

        element.bind("click", handler);

        scope.$on('$destroy', function () {
          element.unbind("click", handler);
        });
      };
    }
  };
}])
```

The original version does not unbind the binding to the directive after a scope got destroyed. This is mostly important on single page apps or if many directives of scrollTo are in use.

**Comment by iameugenejo** [comment]
Thanks for your interest in improving this module.

Though I'm not maintaining this repository actively, (because I don't use AngularJS often anymore), I do manage pull requests.

You can always send a pull request, and you should be able to see the changes applied within a week.

I'll look forward to your merge request for this issue.

Thank you.

**Comment by iameugenejo** [comment]
https://github.com/iameugenejo/ngScrollTo/pull/18 should've covered this issue.
