### ISSUE TITLE
Free from jquery + unbinding elements

### ISSUE THREAD

**Issue by elkami12** [iameugenejo/ngScrollTo#17]
For now this module is insidiously depending on jquery, only for getting offset top property.
By using simple vanilla js it is quite easy to remove that dependency.

Moreover, as said by another follower, elements are not unbound after directive is destroyed.

I am going to create a pull request, hoping that it will be merged.
Thanks for the work !

**Comment by iameugenejo** [comment]
Last time I checked, (it's been a while since the last time I worked on front-end btw), jQuery is required for angularjs. And what jQuery provides that vanilla js does not is browser compatibility. I believe offset calculation is not consistent throughout the various browsers. (This might not be true these days, but at least it was inconsistent back in the days). I'll need to test out your PR, but I want to ask if you have considered browser compatibility when choosing to use a plain JS.

**Comment by tekhedd** [comment]
FYI, Angular ships with a limited subset of jQuery called jqLite, and will use jQuery if it is provided. It may be that you can use these capabilities? I don't personally include jQuery in most of the Angular apps I'm working on.

(Sorry to randomly jump in but apparently I'm watching the project. :)  )

**Comment by iameugenejo** [comment]
@tekhedd: I just did some quick research and found out jqLite does not include jQuery's offset. We maybe able to make use of the PR abandoned by the angular guys - https://github.com/angular/angular.js/pull/3799#issuecomment-212379662, but that will require this module to keep up with the future browser incompatibility. We may be able to make a fallback logic to allow those who do not wish to use full jQuery to use what's provided by this module. I'll see what I can do. Any idea to improve this PR will be appreciated.

**Comment by iameugenejo** [comment]
Merged it now. I'm thinking to amend it with ```var top = ($(el).offset && $(el).offset().top) || (el.getBoundingClientRect().top + el.ownerDocument.body.scrollTop) - offset;``` to prefer jquery offset when it's available. Any thoughts?

**Comment by iameugenejo** [comment]
I decided to leave it as plain js and wait for another PR if there's any compatibility issue. Thanks for your contribution.
